#inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bundle/**/*

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/NumericLiterals:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
